import Link from "next/link";
import { notFound } from "next/navigation";

type Detail = {
  title: string;
  subtitle: string;
  section: string;
  summary: string;
  points: string[];
  impact: string;
  evidence?: { label: string; url: string }[];
  marks?: string[];
};

const details: Record<string, Detail> = {
  "01": { title: "The Student", subtitle: "The everyday attention problem", section: "01 / Student", summary: "A normal student can open a phone for one small task and quickly encounter a stream designed to keep attention moving. VEXORA begins by asking what happens when student technology is optimized for progress rather than retention.", points: ["A task can turn into browsing, recommendations and notifications.", "The important variable is not only screen time, but what the student is trying to accomplish.", "A student-first platform should make the next useful action obvious."], impact: "The design question becomes: does the product help a student finish something, or encourage another session?" },
  "02": { title: "The Attention Economy", subtitle: "Why time became the product", section: "02 / Economy", summary: "Many internet businesses compete for attention because attention can be converted into advertising, engagement and repeated visits. The result is a powerful incentive to reduce friction between one piece of content and the next.", points: ["Engagement can be measured through views, sessions and interactions.", "Recommendation systems can increase the amount of content a person encounters.", "VEXORA takes the opposite design position: success should be measured by useful outcomes."], impact: "A student ecosystem should not need to maximize time-on-platform to prove that it works." },
  "03": { title: "The Algorithm Decides", subtitle: "Recommendation shapes discovery", section: "03 / Algorithms", summary: "Recommendation systems rank what appears next. They can make discovery convenient, but they also mean that a software system becomes part of the information-selection process.", points: ["Ranking determines which items are more visible.", "Personalization can reinforce patterns in what a person watches or clicks.", "VEXORA's social concept favors chronological feeds and intentional discovery instead of an endless personalized stream."], impact: "The interface should support a student's intention instead of silently replacing it with an engagement objective." },
  "04": { title: "The Infinite Feed", subtitle: "Instagram, TikTok and endless scroll", section: "04 / Feeds", summary: "Short-form feeds remove a natural stopping point. One item ends and another is immediately available, creating a continuous loop of consumption.", points: ["Autoplay and scrolling reduce the effort needed to continue.", "Personalized recommendations make the next item unpredictable.", "A stopping point is a product decision, not an accident."], impact: "VEXORA can deliberately use finite tasks, clear completion states and quiet notifications so students can leave when their goal is complete." },
  "05": { title: "What Are We Trading?", subtitle: "Convenience versus attention", section: "05 / Trade-off", summary: "The issue is not that every digital product is harmful. The real question is what a product asks the user to trade for convenience, entertainment or connection.", points: ["Convenience can save time.", "The same convenience can become frictionless consumption.", "A student platform should make learning, building and collaboration easier without making distraction frictionless."], impact: "The trade-off VEXORA wants to change is attention spent versus capability gained." },
  "06": { title: "The Internet Is Changing", subtitle: "A new information environment", section: "06 / Internet", summary: "Search, recommendation, generative AI and synthetic media are changing how information is created and discovered. Students increasingly need both digital literacy and verification skills.", points: ["Information is easier to publish than ever.", "AI can generate text, images, audio and code at scale.", "Verification becomes a core learning skill rather than an optional extra."], impact: "VEXORA should teach students not just how to find information, but how to question, compare and verify it." },
  "07": { title: "AI Slop", subtitle: "When content becomes infinite", section: "07 / AI", summary: "Generative systems can produce huge quantities of low-effort or repetitive material. The term 'AI slop' is informal, but the underlying problem is real: abundance can make useful information harder to distinguish from noise.", points: ["Generation lowers the cost of producing content.", "Volume can overwhelm careful human-created material.", "Students need source awareness, context and quality signals."], impact: "The goal is not to reject AI; it is to teach students to use AI as a tool without surrendering judgment." },
  "08": { title: "Can We Trust What We See?", subtitle: "Verification in the AI era", section: "08 / Verification", summary: "Images, audio, video and text can now be generated or altered convincingly. Trust therefore needs to come from evidence, provenance and corroboration rather than appearance alone.", points: ["Check the original source and date.", "Compare important claims against independent authoritative sources.", "Treat emotionally viral material as something to investigate, not automatically believe."], impact: "VEXORA can make source literacy part of the student experience itself." },
  "09": { title: "The Viral Myth Machine", subtitle: "Viral does not mean verified", section: "09 / Myths", summary: "A claim can spread because it is surprising, emotional or memorable rather than because it is true. VEXORA uses this distinction to teach a simple rule: popularity is not evidence.", points: ["Separate the claim from the story around it.", "Find the earliest credible source available.", "Look for primary documents, institutional evidence and independent confirmation."], impact: "Students should learn to investigate a viral claim before repeating it." },
  "10": { title: "The Digital World", subtitle: "Cybercrime, surveillance and safety", section: "10 / Digital world", summary: "The digital world includes both defensive technologies and serious risks: scams, intrusion, identity theft, foreign intelligence collection and surveillance. This chapter is about understanding the systems behind the headlines without turning them into conspiracy stories.", marks: ["FBI", "PRISM", "XKEYSCORE"], points: ["The FBI is a U.S. federal law-enforcement and national-security agency; its public records include FOIA releases and technical/privacy documentation.", "PRISM is associated with Section 702 collection and provider-assisted acquisition of communications relating to tasked selectors; official NSA documents describe the role of the FBI in providing selectors to service providers.", "XKEYSCORE is an NSA analysis tool. The NSA states that its use is subject to lawful foreign-intelligence authorities, access controls, training and auditing."], impact: "These programs show why students need to understand the difference between a leaked label, an official description, a legal authority and a claim made by a third party.", evidence: [{ label: "FBI — FISA & Section 702", url: "https://www.fbi.gov/how-we-investigate/intelligence/foreign-intelligence-surveillance-act-fisa-and-section-702" }, { label: "FBI Vault — official records", url: "https://vault.fbi.gov/" }, { label: "NSA — XKEYSCORE statement", url: "https://www.nsa.gov/Press-Room/Press-Releases-Statements/Press-Release-View/Article/1618731/nsa-press-statement-in-response-to-allegations-about-nsa-operations/" }, { label: "NSA — Section 702 / PRISM document", url: "https://www.nsa.gov/portals/75/documents/news-features/speeches-testimonies/NSAImplementationofFISA70216Apr2014.FINAL.pdf" }] },
  "11": { title: "Humanity's Unsolved Problems", subtitle: "Questions still at the frontier", section: "11 / Frontier", summary: "Some of the biggest questions in mathematics and science remain open. The existence of unsolved problems is not a failure of education; it is evidence that the frontier is still there to be explored.", points: ["The Millennium Prize Problems demonstrate that major mathematical questions can remain open for decades.", "Research starts with learning the tools that let you ask better questions.", "Students should be exposed to real problems, not only exercises with known answers."], impact: "VEXORA's long-term vision is to connect capable students with problems, communities and mentors beyond their immediate classroom." },
  "12": { title: "Reach the Frontier", subtitle: "Students beyond their classroom", section: "12 / Access", summary: "A student's location should not determine the ceiling of their curiosity. Digital platforms can connect students with resources, competitions, projects and research communities that may not exist locally.", points: ["Open educational resources can extend classroom learning.", "Competitions create structured challenges.", "Projects create evidence of what a student can actually build."], impact: "The ecosystem should turn curiosity into a path: learn → practice → build → compete → collaborate → discover." },
  "13": { title: "The Mentor", subtitle: "A future direction for guidance", section: "13 / Mentorship", summary: "Students often need help deciding what to learn next, how to debug a project or where to find a suitable challenge. VEXORA's future mentorship direction is about guidance, not replacing teachers.", points: ["A mentor should explain and ask questions, not simply provide answers.", "Recommendations should be transparent and goal-driven.", "Human teachers and mentors remain important for judgment, context and care."], impact: "Future AI mentorship should increase student agency rather than create another attention loop." },
  "14": { title: "Student → Researcher", subtitle: "From learning to discovery", section: "14 / Research", summary: "The transition from student to researcher begins when a learner moves from consuming explanations to forming questions, testing ideas and documenting results.", points: ["Learn the foundations.", "Choose a question that can actually be investigated.", "Record methods, evidence, failures and conclusions.", "Share work so others can reproduce or challenge it."], impact: "VEXORA can make the research process visible and achievable for students." },
  "15": { title: "Not Another Learning App", subtitle: "Why VEXORA is an ecosystem", section: "15 / VEXORA", summary: "VEXORA is designed around the idea that learning is only one part of student success. Students also need opportunities to build, compete, lead, collaborate and show what they can do.", points: ["Learning provides knowledge.", "Projects turn knowledge into capability.", "Competitions and communities create challenge and connection.", "Portfolios make progress visible."], impact: "The platform should connect these parts instead of splitting them across unrelated services." },
  "16": { title: "The VEXORA Ecosystem", subtitle: "Learning, projects and opportunity", section: "16 / Ecosystem", summary: "The long-term ecosystem can combine learning, competitions, innovation, scholarships, communities, career development, portfolios and impact tracking.", points: ["Learn: structured courses and school support.", "Build: projects and practical challenges.", "Compete: olympiads, hackathons and competitions.", "Connect: communities and collaboration.", "Grow: portfolios, opportunities and pathways."], impact: "The value comes from the connections between these pieces, not from any single feature." },
  "17": { title: "A Different Social Network", subtitle: "Connection without attention traps", section: "17 / Network", summary: "VEXORA's community layer should borrow the useful part of social networks—connection—without copying mechanics that encourage endless consumption or popularity contests.", points: ["Chronological feeds instead of algorithmic 'For You' ranking.", "No public follower race as the primary measure of status.", "Replies and thoughtful discussion over vanity metrics.", "Quiet notifications and intentional communities."], impact: "Social connection becomes a means to collaborate, not a reason to stay online indefinitely." },
  "18": { title: "Consumption → Creation", subtitle: "Build instead of endlessly scroll", section: "18 / Creation", summary: "The strongest alternative to passive consumption is purposeful creation. A student who watches a coding tutorial can go one step further and build a program; a science lesson can become an experiment.", points: ["Every learning path should have a possible creation outcome.", "Projects create durable evidence of skill.", "Sharing work should invite useful feedback rather than popularity competition."], impact: "The platform's success metric becomes capability created, not minutes consumed." },
  "19": { title: "A National Network", subtitle: "Connecting student potential", section: "19 / Network", summary: "VEXORA's largest ambition is a student ecosystem that can connect learners across schools, regions and institutions while respecting safety, privacy and local context.", points: ["Students can discover opportunities outside their immediate school.", "Institutions can surface competitions, programs and pathways.", "Student portfolios can help make capability visible beyond grades alone."], impact: "A national network can reduce geographic isolation while keeping the student's goals at the center." },
  "20": { title: "The Future", subtitle: "The long-term vision", section: "20 / Future", summary: "VEXORA is not presented as a finished product. It is a direction: build technology that gives students more capability, more opportunity and more control over their attention.", points: ["Learn with purpose.", "Build real things.", "Lead and collaborate.", "Reach opportunities and frontier questions.", "Use technology without becoming dependent on it."], impact: "The final question is simple: after using VEXORA, what can a student do that they could not do before?" },
};

export function generateStaticParams() { return Object.keys(details).map((chapter) => ({ chapter })); }

export default async function ChapterDetail({ params }: { params: Promise<{ chapter: string }> }) {
  const { chapter } = await params;
  const detail = details[chapter];
  if (!detail) notFound();
  const previous = String(Number(chapter) - 1).padStart(2, "0");
  const next = String(Number(chapter) + 1).padStart(2, "0");
  return <main className="detail-page">
    <header className="detail-nav"><Link href="/case-study">← All chapters</Link><span>VEXORA / CASE STUDY</span><Link href="/">VEXORA ↗</Link></header>
    <article className="detail-shell">
      <p className="eyebrow">{detail.section}</p>
      <div className="detail-title-row"><div><h1>{detail.title}</h1><p className="detail-subtitle">{detail.subtitle}</p></div><span className="detail-index">{chapter}</span></div>
      {detail.marks && <div className="evidence-marks">{detail.marks.map(mark => <span key={mark}>{mark}</span>)}</div>}
      <div className="detail-grid">
        <div><p className="detail-label">THE IDEA</p><p className="detail-lead">{detail.summary}</p></div>
        <aside className="detail-note"><span>WHY IT MATTERS</span><p>{detail.impact}</p></aside>
      </div>
      <section className="detail-section"><p className="detail-label">KEY DETAILS</p><div className="detail-points">{detail.points.map((point, i) => <div key={point}><b>{String(i + 1).padStart(2, "0")}</b><p>{point}</p></div>)}</div></section>
      {detail.evidence && <section className="detail-section evidence"><p className="detail-label">PRIMARY / OFFICIAL DOCUMENTS</p><p className="evidence-intro">Use the original record wherever possible. For surveillance topics, this page deliberately separates official descriptions from outside interpretations.</p><div className="evidence-links">{detail.evidence.map(item => <a href={item.url} target="_blank" rel="noreferrer" key={item.url}><span>{item.label}</span><b>↗</b></a>)}</div></section>}
      <div className="detail-footer"><Link href={Number(chapter) > 1 ? `/case-study/${previous}` : "/case-study"}>← Previous</Link><Link href="/case-study">Chapter index</Link><Link href={Number(chapter) < 20 ? `/case-study/${next}` : "/case-study"}>Next →</Link></div>
    </article>
  </main>;
}
