import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import axios from "axios";
import "./styles.css";

const API=import.meta.env.VITE_API_URL||"http://127.0.0.1:8000/api";
const api=axios.create({baseURL:API});
api.interceptors.request.use(c=>{const t=localStorage.getItem("vexora_token");if(t)c.headers.Authorization=`Token ${t}`;return c});
const communities=["Coding","Space & Astronomy","Game Development","Mathematics","Design","Science"];
const demoPeople=["Ariyan Builds","Nethmi Designs","Ravin Codes","Sahan Space","Kavya Math"];

function App(){
 const [auth,setAuth]=useState(!!localStorage.getItem("vexora_token")),[tab,setTab]=useState("Home"),[me,setMe]=useState(null),[posts,setPosts]=useState([]),[stories,setStories]=useState([]),[notice,setNotice]=useState("");
 const refresh=async()=>{if(!auth)return;try{const [f,s,m]=await Promise.all([api.get("/feed/"),api.get("/stories/"),api.get("/auth/me/")]);setPosts(f.data);setStories(s.data);setMe(m.data)}catch(e){if(e.response?.status===401){localStorage.removeItem("vexora_token");setAuth(false)}}};
 useEffect(()=>{refresh()},[auth]);
 const flash=x=>{setNotice(x);setTimeout(()=>setNotice(""),2200)};
 const logout=async()=>{try{await api.post("/auth/logout/")}catch{}localStorage.removeItem("vexora_token");setAuth(false)};
 if(!auth)return <Auth onAuth={()=>setAuth(true)}/>;
 return <div className="app"><aside><div className="logo">VEXORA<span>✦</span></div>{["Home","Discover","Create","Reels","Messages","Communities","Notifications","Profile"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}><i>{icon(x)}</i><span>{x}</span></button>)}<button className="logout" onClick={logout}>↪ <span>Log out</span></button></aside><main><header><b>{tab}</b><small>VEXORA · student social network</small></header>{notice&&<div className="toast">{notice}</div>}
 {tab==="Home"&&<Home me={me} posts={posts} stories={stories} refresh={refresh} flash={flash}/>}
 {tab==="Discover"&&<Discover flash={flash}/>}
 {tab==="Create"&&<Create refresh={refresh} flash={flash}/>}
 {tab==="Reels"&&<Reels/>}{tab==="Messages"&&<Messages flash={flash}/>}
 {tab==="Communities"&&<Communities/>}{tab==="Notifications"&&<Notifications/>}{tab==="Profile"&&<Profile me={me} posts={posts}/>}
 </main><nav className="mobile">{["Home","Discover","Create","Messages","Profile"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{icon(x)}<small>{x}</small></button>)}</nav></div>
}
function icon(x){return ({Home:"⌂",Discover:"⌕",Create:"+",Reels:"▶",Messages:"◌",Communities:"◎",Notifications:"♡",Profile:"◉"}[x]||"•")}
function Auth({onAuth}){const [mode,setMode]=useState("login"),[u,setU]=useState(""),[p,setP]=useState(""),[err,setErr]=useState("");const submit=async e=>{e.preventDefault();setErr("");try{const r=await axios.post(`${API}/auth/${mode}/`,{username:u,password:p});localStorage.setItem("vexora_token",r.data.token);onAuth()}catch(e){setErr(e.response?.data?.detail||"Could not connect to VEXORA.")}};return <div className="auth"><form onSubmit={submit}><div className="authlogo">VEXORA✦</div><h1>{mode==="login"?"Welcome back.":"Join VEXORA."}</h1><p>Discover creators. Share ideas. Find your people.</p><input value={u} onChange={e=>setU(e.target.value)} placeholder="Username"/><input type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Password"/>{err&&<em>{err}</em>}<button className="primary">{mode==="login"?"Log in":"Create account"}</button><button type="button" className="link" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Create an account":"Back to login"}</button></form></div>}
function Home({me,posts,stories,refresh,flash}){const [text,setText]=useState("");const publish=async()=>{if(!text.trim())return;try{await api.post("/posts/",{caption:text.trim()});setText("");refresh();flash("Posted.")}catch{flash("Django API is unavailable.")}};return <section className="feed"><div className="stories">{[{author:me?.username||"You"},...stories].slice(0,8).map((s,i)=><div className="story" key={i}><div>{s.author.slice(0,2).toUpperCase()}</div><small>{i===0?"Your story":s.author}</small></div>)}</div><div className="composer"><div className="avatar">{(me?.username||"VT").slice(0,2).toUpperCase()}</div><input value={text} onChange={e=>setText(e.target.value)} placeholder="Share a project, idea or question..."/><button onClick={publish}>Share</button></div><div className="tabs"><b>For you</b><span>Following</span></div>{posts.map(p=><Post key={p.id} p={p} refresh={refresh} flash={flash}/>)}{!posts.length&&<div className="empty"><b>✦</b><h2>Your feed starts here.</h2><p>Be the first to share a project, idea or question.</p></div>}</section>}
function Post({p,refresh,flash}){const [c,setC]=useState("");const like=async()=>{try{await api.post(`/posts/${p.id}/like/`);refresh()}catch{flash("Like failed.")}};const comment=async()=>{if(!c.trim())return;try{await api.post(`/posts/${p.id}/comment/`,{text:c.trim()});setC("");refresh()}catch{flash("Comment failed.")}};return <article className="post"><div className="posthead"><div className="avatar">{p.author.slice(0,2).toUpperCase()}</div><div><b>@{p.author}</b><small>Student creator · VEXORA</small></div><span>•••</span></div><div className="art"><div>V</div><b>BUILD · SHARE · CONNECT</b><small>PROJECT SHOWCASE</small></div><div className="actions"><button className={p.liked?"liked":""} onClick={like}>{p.liked?"♥":"♡"}</button><button>◯</button><button>↗</button><button>⌑</button></div><div className="body"><b>{p.likes_count} likes</b><p><strong>@{p.author}</strong> {p.caption}</p>{p.comments?.slice(-2).map(x=><div className="comment" key={x.id}><b>@{x.author}</b> {x.text}</div>)}<small>{p.comments?.length||0} comments</small><div className="commentbox"><input value={c} onChange={e=>setC(e.target.value)} onKeyDown={e=>e.key==="Enter"&&comment()} placeholder="Add a comment..."/><button onClick={comment}>Post</button></div></div></article>}
function Create({refresh,flash}){const [text,setText]=useState("");const publish=async()=>{if(!text.trim())return;try{await api.post("/posts/",{caption:text.trim()});setText("");refresh();flash("Published to VEXORA.")}catch{flash("Could not publish.")}};return <section className="panel"><label>CREATE</label><h1>Make something worth sharing.</h1><p>Projects, experiments, questions, ideas and discoveries.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="What's happening in your world?"/><div className="row"><button>＋ Add media</button><button>⌁ Topic</button><button className="primary" onClick={publish}>Publish</button></div></section>}
function Discover({flash}){const [q,setQ]=useState("");return <section><div className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people, projects, communities and topics"/></div><div className="discoverhero"><div><label>DISCOVER</label><h1>Find your people.</h1><p>Student creators, communities and ideas built around curiosity.</p></div><div className="chips">{["CODE","SPACE","MATH","DESIGN"].map(x=><b key={x}>{x}</b>)}</div></div><h2>People to connect with</h2>{demoPeople.filter(x=>x.toLowerCase().includes(q.toLowerCase())).map((x,i)=><div className="person" key={x}><div className="avatar">{x.slice(0,2).toUpperCase()}</div><div><b>{x}</b><small>Student creator · building in public</small></div><button onClick={()=>api.post("/follow/",{user_id:i+1}).then(()=>flash("Follow state updated.")).catch(()=>flash("Create another user first."))}>Follow</button></div>)}<h2>Trending communities</h2><div className="cards">{communities.map(x=><div className="community" key={x}><label>COMMUNITY</label><h3>{x}</h3><p>Projects · questions · collaboration</p><button>Join</button></div>)}</div></section>}
function Reels(){return <section><label>SHORT-FORM CREATION</label><h1>Reels, but purposeful.</h1><p>Quick project demos, experiments, explainers and student-made ideas.</p><div className="reels">{["BUILD","SPACE","CODE","CREATE","MATH","ART"].map(x=><div key={x}><strong>▶</strong><b>{x}</b><small>Student creation</small></div>)}</div></section>}
function Messages({flash}){const [items,setItems]=useState([]),[text,setText]=useState("");const load=()=>api.get("/messages/").then(r=>setItems(r.data)).catch(()=>{});useEffect(load,[]);const send=async()=>{if(!text.trim())return;try{await api.post("/messages/",{recipient_id:1,text:text.trim()});setText("");load()}catch{flash("Create a second account to message someone.")}};return <section className="messages"><div className="inbox"><h2>Messages</h2><div className="thread active"><div className="avatar">AR</div><b>Ariyan Builds<small>Project collaboration</small></b></div><div className="thread"><div className="avatar">SS</div><b>Sahan Space<small>Space & Astronomy</small></b></div></div><div className="chat"><header><b>Collaboration</b><small>VEXORA messages</small></header><div className="chatbody">{items.length?items.map(m=><div className="bubble" key={m.id}><b>@{m.sender}</b><br/>{m.text}</div>):<p>Start a project conversation.</p>}</div><div className="chatinput"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Message..."/><button onClick={send}>Send</button></div></div></section>}
function Communities(){return <section><label>COMMUNITIES</label><h1>Find your corner of VEXORA.</h1><div className="cards">{communities.map(x=><div className="community big" key={x}><label>STUDENTS</label><h2>{x}</h2><p>Share work. Ask questions. Find collaborators.</p><button>Join community</button></div>)}</div></section>}
function Notifications(){const [n,setN]=useState([]);useEffect(()=>{api.get("/notifications/").then(r=>setN(r.data)).catch(()=>{})},[]);return <section className="panel"><label>ACTIVITY</label><h1>Notifications</h1>{n.length?n.map(x=><div className="notification" key={x.id}>♡ {x.text}</div>):<p>You're all caught up.</p>}</section>}
function Profile({me,posts}){const mine=posts.filter(p=>p.author===me?.username);return <section className="profile"><div className="cover"></div><div className="profrow"><div className="avatar big">{(me?.username||"VT").slice(0,2).toUpperCase()}</div><button>Edit profile</button></div><h1>@{me?.username}</h1><p>{me?.bio||"Student creator · building things and finding people to build with."}</p><div className="stats"><b>{mine.length}<small>posts</small></b><b>{me?.followers_count||0}<small>followers</small></b><b>{me?.following_count||0}<small>following</small></b></div><div className="profilegrid">{mine.map(p=><div key={p.id}>VEXORA<small>{p.caption}</small></div>)}</div></section>}
createRoot(document.getElementById("root")).render(<App/>);
