
'use client';

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";

type Comment={id:number;name:string;text:string};
type Post={id:number;name:string;initials:string;time:string;image:string;caption:string;likes:number;comments:number;liked?:boolean;saved?:boolean;topic:string;commentsList:Comment[]};

const seedPosts:Post[]=[
{id:1,name:"Ariyan Builds",initials:"AB",time:"18m",image:"PROJECT",caption:"Finally got my ESP32 sensor dashboard working ⚡ What should I add next?",likes:284,comments:31,topic:"Technology",commentsList:[{id:1,name:"Nethmi Designs",text:"This looks awesome! Add a temperature graph."},{id:2,name:"Ravin Codes",text:"Maybe a mobile controller next 👀"}]},
{id:2,name:"VEXORA Space",initials:"VS",time:"42m",image:"SPACE",caption:"If you could send one question to the universe, what would you ask? 🌌",likes:612,comments:74,topic:"Space",commentsList:[{id:3,name:"Sahan Space",text:"What happened before the Big Bang?"},{id:4,name:"Kavya Math",text:"How does consciousness fit into the universe?"}]},
{id:3,name:"Kavya Math",initials:"KM",time:"1h",image:"MATH",caption:"Olympiad problem of the day. No calculator. Can you solve it?",likes:173,comments:26,topic:"Mathematics",commentsList:[{id:5,name:"Ariyan Builds",text:"I got 42. Is that right?"}]}
];
const storyData=[["VT","You"],["AB","Ariyan"],["VS","VEXORA"],["KM","Kavya"],["RJ","Ravin"],["ND","Nethmi"],["SS","Sahan"]];
const people=["Nethmi Designs","Ravin Codes","Sahan Space","Kavya Math","Ariyan Builds"];
const communities=["Coding","Space & Astronomy","Game Development","Mathematics","Design","Science"];

export default function Prototype(){
 const [posts,setPosts]=useState<Post[]>(seedPosts),[tab,setTab]=useState("Home"),[composer,setComposer]=useState(""),[joined,setJoined]=useState<string[]>([]),[notice,setNotice]=useState(""),[following,setFollowing]=useState<string[]>([]),[saved,setSaved]=useState<number[]>([]),[story,setStory]=useState<string|null>(null),[search,setSearch]=useState(""),[profileName,setProfileName]=useState("Your Profile"),[bio,setBio]=useState("Building things, exploring ideas and finding people to build with."),[editProfile,setEditProfile]=useState(false),[commentPost,setCommentPost]=useState<number|null>(null),[commentText,setCommentText]=useState(""),[message,setMessage]=useState(""),[chat,setChat]=useState<string[]>(["Can you check my new project? ⚡","Sure! Send it here."]);
 const fileRef=useRef<HTMLInputElement|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem("vexora-demo");if(raw){const x=JSON.parse(raw);if(x.posts)setPosts(x.posts);if(x.following)setFollowing(x.following);if(x.joined)setJoined(x.joined);if(x.saved)setSaved(x.saved);if(x.profileName)setProfileName(x.profileName);if(x.bio)setBio(x.bio)}}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("vexora-demo",JSON.stringify({posts,following,joined,saved,profileName,bio}))}catch{}},[posts,following,joined,saved,profileName,bio]);
 const notify=(x:string)=>{setNotice(x);window.setTimeout(()=>setNotice(""),2600)};
 const like=(id:number)=>setPosts(ps=>ps.map(p=>p.id===id?{...p,liked:!p.liked,likes:p.likes+(p.liked?-1:1)}:p));
 const savePost=(id:number)=>{setPosts(ps=>ps.map(p=>p.id===id?{...p,saved:!p.saved}:p));setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);notify(saved.includes(id)?"Removed from saved":"Saved to your collection");};
 const toggleFollow=(name:string)=>{setFollowing(f=>f.includes(name)?f.filter(x=>x!==name):[...f,name]);notify(following.includes(name)?"Unfollowed "+name:"Following "+name)};
 const publish=()=>{if(!composer.trim()){notify("Write something before posting.");return}setPosts(ps=>[{id:Date.now(),name:profileName,initials:"VT",time:"now",image:"YOUR POST",caption:composer.trim(),likes:0,comments:0,topic:"Community",commentsList:[]},...ps]);setComposer("");notify("Your post is live");setTab("Home")};
 const addComment=(id:number)=>{if(!commentText.trim())return;setPosts(ps=>ps.map(p=>p.id===id?{...p,comments:p.comments+1,commentsList:[...p.commentsList,{id:Date.now(),name:profileName,text:commentText.trim()}]}:p));setCommentText("");notify("Comment added")};
 const share=(p:Post)=>{const text=p.name+" on VEXORA: "+p.caption;if(navigator.share)navigator.share({title:"VEXORA",text}).catch(()=>{});else navigator.clipboard?.writeText(text).then(()=>notify("Post text copied"));};
 const nav=[["Home","⌂"],["Discover","⌕"],["Create","＋"],["Reels","▶"],["Messages","✉"],["Profile","VT"]];
 return <main className="ig-shell">
  <aside className="ig-sidebar"><Link href="/" className="ig-logo">VEXORA</Link><nav>{nav.map(([n,icon])=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}><b>{icon}</b><span>{n}</span>{n==="Messages"&&<i>3</i>}</button>)}</nav><div className="side-bottom"><button onClick={()=>setTab("Communities")}><b>◉</b><span>Communities</span></button><button onClick={()=>setTab("Notifications")}><b>♢</b><span>Notifications</span></button><button onClick={()=>setTab("Saved")}><b>⌑</b><span>Saved</span></button><Link href="/case-study">Case Study ↗</Link></div></aside>
  <div className="ig-mobile-top"><Link href="/" className="ig-logo">VEXORA</Link><div><button onClick={()=>setTab("Notifications")}>♡</button><button onClick={()=>setTab("Messages")}>✉</button></div></div>
  <section className="ig-main">
   {notice&&<button className="ig-toast" onClick={()=>setNotice("")}>{notice} ×</button>}
   {tab==="Home"&&<Home stories={storyData} posts={posts} composer={composer} setComposer={setComposer} publish={publish} like={like} save={savePost} share={share} setTab={setTab} setStory={setStory} setCommentPost={setCommentPost}/>}
   {tab==="Discover"&&<Discover search={search} setSearch={setSearch} toggleFollow={toggleFollow} following={following} setTab={setTab}/>}
   {tab==="Create"&&<Create composer={composer} setComposer={setComposer} publish={publish} fileRef={fileRef}/>}
   {tab==="Reels"&&<Reels notify={notify}/>}
   {tab==="Messages"&&<Messages message={message} setMessage={setMessage} chat={chat} setChat={setChat}/>}
   {tab==="Profile"&&<Profile name={profileName} bio={bio} setTab={setTab} onEdit={()=>setEditProfile(true)} posts={posts.filter(p=>p.name===profileName)} saved={saved}/>}
   {tab==="Communities"&&<Communities joined={joined} setJoined={setJoined}/>}
   {tab==="Notifications"&&<Notifications/>}
   {tab==="Saved"&&<Saved posts={posts.filter(p=>saved.includes(p.id))} setTab={setTab}/>}
  </section>
  <aside className="ig-right"><ProfileMini name={profileName}/><div className="right-title">Suggested for you <button onClick={()=>setTab("Discover")}>See All</button></div>{people.slice(0,3).map((x,i)=><div className="suggest" key={x}><div className="avatar">{"ND RC SS".split(" ")[i]}</div><span><strong>{x}</strong><small>{["UI Designer","Python Builder","Astronomy"][i]}</small></span><button onClick={()=>toggleFollow(x)}>{following.includes(x)?"Following":"Follow"}</button></div>)}<div className="right-title space">Trending communities</div>{communities.slice(0,4).map(x=><button className="trend" key={x} onClick={()=>setJoined(j=>j.includes(x)?j.filter(a=>a!==x):[...j,x])}><span>#{x.replaceAll(" ","")}</span><small>{joined.includes(x)?"Joined":"Join"}</small></button>)}<footer>© 2026 VEXORA · Privacy · About · Communities · Case Study</footer></aside>
  {story&&<StoryViewer story={story} close={()=>setStory(null)}/>}
  {commentPost!==null&&<CommentModal post={posts.find(p=>p.id===commentPost)!} text={commentText} setText={setCommentText} add={()=>addComment(commentPost)} close={()=>setCommentPost(null)}/>}
  {editProfile&&<EditProfile name={profileName} bio={bio} setName={setProfileName} setBio={setBio} close={()=>setEditProfile(false)} save={()=>{setEditProfile(false);notify("Profile updated")}}/>}
 </main>
}

function ProfileMini({name}:{name:string}){return <div className="profile-mini"><div className="avatar big">VT</div><span><strong>{name}</strong><small>@yourprofile · Student creator</small></span><button>Switch</button></div>}
function Home({stories,posts,composer,setComposer,publish,like,save,share,setTab,setStory,setCommentPost}:{stories:string[][];posts:Post[];composer:string;setComposer:(x:string)=>void;publish:()=>void;like:(x:number)=>void;save:(x:number)=>void;share:(p:Post)=>void;setTab:(x:string)=>void;setStory:(x:string)=>void;setCommentPost:(x:number)=>void}){return <div className="home"><div className="stories">{stories.map(([initials,name])=><button key={name} onClick={()=>setStory(name)}><div className="story-ring"><div className="avatar">{initials}</div></div><span>{name}</span></button>)}</div><section className="quick-create"><div className="avatar">VT</div><input value={composer} onChange={e=>setComposer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&publish()} placeholder="Share a project, idea, question..."/><button onClick={publish}>Post</button></section><div className="feed-label"><strong>For you</strong><button onClick={()=>setTab("Discover")}>Following</button></div>{posts.map(p=><article className="ig-post" key={p.id}><header><div className="avatar">{p.initials}</div><div><strong>{p.name}</strong><span>{p.time} · {p.topic}</span></div><button onClick={()=>alert("Post options: Save, Share, Report")}>•••</button></header><div className={"post-art "+p.image.toLowerCase().replaceAll(" ","-")}><div><span>{p.image==="SPACE"?"✦":p.image==="MATH"?"∑":"⌁"}</span><strong>{p.image==="SPACE"?"EXPLORE THE UNIVERSE":p.image==="MATH"?"THINK DIFFERENT":"BUILD SOMETHING"}</strong><small>VEXORA</small></div></div><div className="post-tools"><button className={p.liked?"red":""} onClick={()=>like(p.id)}>{p.liked?"♥":"♡"}</button><button onClick={()=>setCommentPost(p.id)}>◌</button><button onClick={()=>share(p)}>↗</button><button className={"save "+(p.saved?"saved":"")} onClick={()=>save(p.id)}>⌑</button></div><div className="post-likes">{p.likes.toLocaleString()} likes</div><p><strong>{p.name}</strong> {p.caption}</p><button className="comments" onClick={()=>setCommentPost(p.id)}>View all {p.comments} comments</button><div className="comment-box"><input placeholder="Add a comment..." onFocus={()=>setCommentPost(p.id)}/><button onClick={()=>setCommentPost(p.id)}>Post</button></div></article>)}</div>}
function Discover({search,setSearch,toggleFollow,following,setTab}:{search:string;setSearch:(x:string)=>void;toggleFollow:(x:string)=>void;following:string[];setTab:(x:string)=>void}){const filtered=useMemo(()=>people.filter(x=>x.toLowerCase().includes(search.toLowerCase())),[search]);return <div className="explore"><h1>Discover</h1><div className="search-big">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people, projects, communities and topics"/></div><div className="explore-grid">{["CODING","SPACE","DESIGN","GAMES","MATH","SCIENCE","HARDWARE","ART"].map((x,i)=><button key={x} onClick={()=>setTab("Communities")} className={"explore-tile t"+i}><span>{["⌘","✦","◇","△","∑","⚗","⌁","✧"][i]}</span><strong>{x}</strong></button>)}</div><h2>People you may know</h2><div className="people-grid">{filtered.map((x,i)=><div className="people-card" key={x}><div className="avatar big">{["ND","RC","SS","KM","AB"][i]}</div><strong>{x}</strong><small>Student creator · {["Design","Coding","Space","Mathematics","Hardware"][i]}</small><button onClick={()=>toggleFollow(x)}>{following.includes(x)?"Following":"Follow"}</button></div>)}</div></div>}
function Create({composer,setComposer,publish,fileRef}:{composer:string;setComposer:(x:string)=>void;publish:()=>void;fileRef:React.RefObject<HTMLInputElement|null>}){return <div className="create-page"><h1>Create</h1><div className="create-box"><div className="create-preview"><div className="post-art YOUR-POST"><div><span>＋</span><strong>Your post</strong><small>PROJECT · IDEA · QUESTION</small></div></div></div><div className="create-form"><div className="create-author"><div className="avatar">VT</div><strong>Your Profile</strong></div><textarea value={composer} onChange={e=>setComposer(e.target.value)} placeholder="Write a caption, idea or question..."/><div className="create-options"><button onClick={()=>fileRef.current?.click()}>▧ Add photo</button><button onClick={()=>setComposer(composer+" #Project")}>◈ Project</button><button onClick={()=>setComposer(composer+" #Topic")}># Topic</button><button onClick={()=>setComposer(composer+" #Opportunity")}>⌁ Opportunity</button></div><input ref={fileRef} type="file" accept="image/*" hidden onChange={()=>{}}/><button className="share-btn" onClick={publish}>Share to VEXORA</button></div></div></div>}
function Reels({notify}:{notify:(x:string)=>void}){const rs=["BUILD","SPACE","CODE","CREATE","MATH","ART"];return <div className="reels"><h1>Reels</h1><p>Short creative videos from students — prototypes, experiments, art, science and ideas.</p><div className="reel-grid">{rs.map((x,i)=><div className={"reel r"+i} key={x}><span>{["▶","✦","⌘","⚡","∑","✧"][i]}</span><strong>{x}</strong><small>VEXORA</small><button onClick={()=>notify("Playing "+x+" reel")}>▶</button><div className="reel-actions\"><button onClick={()=>notify("Liked "+x+" reel")}>♡</button><button onClick={()=>notify("Shared "+x+" reel")}>↗</button></div></div>)}</div></div>}
function Messages({message,setMessage,chat,setChat}:{message:string;setMessage:(x:string)=>void;chat:string[];setChat:(x:string[])=>void}){const send=()=>{if(!message.trim())return;setChat([...chat,message.trim()]);setMessage("")};return <div className="messages"><h1>Messages</h1><div className="dm-panel"><div className="dm-list">{["Ariyan Builds","VEXORA Team","Kavya Math"].map((x,i)=><button key={x} className={i===0?"active":""}><div className="avatar">{"AB VT KM".split(" ")[i]}</div><span><strong>{x}</strong><small>{i===0?"Can you check my project?":"New message"}</small></span></button>)}</div><div className="dm-chat"><div className="chat-top"><div className="avatar">AB</div><strong>Ariyan Builds</strong></div>{chat.map((x,i)=><div className={"chat-bubble "+(i%2?"mine":"")} key={i}>{x}</div>)}<div className="chat-input"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Message..."/><button onClick={send}>Send</button></div></div></div></div>}
function Communities({joined,setJoined}:{joined:string[];setJoined:(x:string[])=>void}){return <div className="communities"><h1>Communities</h1><p>Find your people. Build around what you care about.</p><div className="community-grid">{communities.map((x,i)=><article key={x}><div className="community-art">{["⌘","✦","△","∑","◇","⚗"][i]}</div><h2>{x}</h2><span>{[2400,1800,1200,980,740,630][i].toLocaleString()} students</span><p>Share work, ask questions and collaborate with students interested in {x.toLowerCase()}.</p><button onClick={()=>setJoined(joined.includes(x)?joined.filter(a=>a!==x):[...joined,x])}>{joined.includes(x)?"Joined ✓":"Join"}</button></article>)}</div></div>}
function Notifications(){return <div className="notifications"><h1>Notifications</h1>{["Ariyan liked your project.","Kavya commented on your post.","VEXORA Team invited you to Coding.","Sahan started following you.","Innovation Showcase is now open."].map((x,i)=><div className="notification" key={x}><div className="avatar">{["♡","◌","⌘","＋","★"][i]}</div><span><strong>{x}</strong><small>{i+1}h ago</small></span><button>›</button></div>)}</div>}
function Profile({name,bio,setTab,onEdit,posts,saved}:{name:string;bio:string;setTab:(x:string)=>void;onEdit:()=>void;posts:Post[];saved:number[]}){return <div className="profile-page"><div className="profile-cover"></div><div className="profile-head"><div className="avatar profile-avatar">VT</div><div><h1>{name}</h1><span>@yourprofile · Student creator</span><p>{bio}</p></div><button onClick={onEdit}>Edit profile</button></div><div className="profile-stats"><b>{posts.length}</b> posts <b>1.2K</b> followers <b>{saved.length}</b> saved</div><div className="profile-tabs"><button>Posts</button><button>Projects</button><button>Communities</button><button>About</button></div><div className="profile-content"><h2>Your projects</h2><div className="mini-projects">{["NFC Jukebox","CPU Simulator","VEXORA"].map(x=><div key={x}><div className="project-art">{x.slice(0,2)}</div><strong>{x}</strong><small>Project · VEXORA</small></div>)}</div></div></div>}
function Saved({posts,setTab}:{posts:Post[];setTab:(x:string)=>void}){return <div className="saved-page"><h1>Saved</h1>{posts.length?<div>{posts.map(p=><article className="saved-row" key={p.id}><div className="avatar">{p.initials}</div><span><strong>{p.name}</strong><small>{p.caption}</small></span><button onClick={()=>setTab("Home")}>View</button></article>)}</div>:<div className="empty-state\"><div>⌑</div><h2>Save posts for later</h2><p>When you save a project, idea or opportunity, it will appear here.</p></div>}</div>}
function StoryViewer({story,close}:{story:string;close:()=>void}){return <div className="modal-backdrop story-modal" onClick={close}><div className="story-view" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><div className="story-progress"></div><div className="story-center"><div className="story-avatar">{story.slice(0,2).toUpperCase()}</div><h2>{story}</h2><p>Student creator · VEXORA story</p><div className="story-art">✦</div></div></div></div>}
function CommentModal({post,text,setText,add,close}:{post:Post;text:string;setText:(x:string)=>void;add:()=>void;close:()=>void}){return <div className="modal-backdrop" onClick={close}><div className="comment-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><h2>Comments</h2><p className="comment-caption"><b>{post.name}</b> {post.caption}</p><div className="comment-list">{post.commentsList.map(c=><div className="comment" key={c.id}><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><span><b>{c.name}</b> {c.text}</span></div>)}</div><div className="comment-compose"><input autoFocus value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Add a comment..."/><button onClick={add}>Post</button></div></div></div>}
function EditProfile({name,bio,setName,setBio,close,save}:{name:string;bio:string;setName:(x:string)=>void;setBio:(x:string)=>void;close:()=>void;save:()=>void}){const [n,setN]=useState(name),[b,setB]=useState(bio);return <div className="modal-backdrop" onClick={close}><div className="edit-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><h2>Edit profile</h2><label>Name<input value={n} onChange={e=>setN(e.target.value)}/></label><label>Bio<textarea value={b} onChange={e=>setB(e.target.value)}/></label><button className="share-btn" onClick={()=>{setName(n);setBio(b);save()}}>Save changes</button></div></div>}
