'use client';

import Link from "next/link";
import { useState } from "react";

type Post={id:number;name:string;initials:string;time:string;image:string;caption:string;likes:number;comments:number;liked?:boolean;topic:string};
const initialPosts:Post[]=[
{id:1,name:"Ariyan Builds",initials:"AB",time:"18m",image:"PROJECT",caption:"Finally got my ESP32 sensor dashboard working ⚡ What should I add next?",likes:284,comments:31,topic:"Technology"},
{id:2,name:"VEXORA Space",initials:"VS",time:"42m",image:"SPACE",caption:"If you could send one question to the universe, what would you ask? 🌌",likes:612,comments:74,topic:"Space"},
{id:3,name:"Kavya Math",initials:"KM",time:"1h",image:"MATH",caption:"Olympiad problem of the day. No calculator. Can you solve it?",likes:173,comments:26,topic:"Mathematics"}
];
const stories=[["VT","You"],["AB","Ariyan"],["VS","VEXORA"],["KM","Kavya"],["RJ","Ravin"],["NP","Nethmi"],["SK","Sahan"]];

export default function Prototype(){
 const [posts,setPosts]=useState(initialPosts),[tab,setTab]=useState("Home"),[composer,setComposer]=useState(""),[joined,setJoined]=useState<string[]>([]),[notice,setNotice]=useState("");
 const like=(id:number)=>setPosts(ps=>ps.map(p=>p.id===id?{...p,liked:!p.liked,likes:p.likes+(p.liked?-1:1)}:p));
 const publish=()=>{if(!composer.trim()){setNotice("Write something before posting.");return}setPosts(ps=>[{id:Date.now(),name:"Your Profile",initials:"VT",time:"now",image:"YOUR POST",caption:composer.trim(),likes:0,comments:0,topic:"Community"},...ps]);setComposer("");setNotice("Your post is live.");setTab("Home")};
 const nav=[["Home","⌂"],["Discover","⌕"],["Create","＋"],["Reels","▶"],["Messages","♡"],["Profile","VT"]];
 return <main className="ig-shell">
  <aside className="ig-sidebar">
   <Link href="/" className="ig-logo">VEXORA</Link>
   <nav>{nav.map(([n,icon])=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}><b>{icon}</b><span>{n}</span>{n==="Messages"&&<i>3</i>}</button>)}</nav>
   <div className="side-bottom"><button onClick={()=>setTab("Communities")}><b>◉</b><span>Communities</span></button><button onClick={()=>setTab("Notifications")}><b>♢</b><span>Notifications</span></button><Link href="/case-study">Case Study ↗</Link></div>
  </aside>
  <div className="ig-mobile-top"><Link href="/" className="ig-logo">VEXORA</Link><div><button onClick={()=>setTab("Notifications")}>♡</button><button onClick={()=>setTab("Messages")}>✉</button></div></div>
  <section className="ig-main">
   {notice&&<button className="ig-toast" onClick={()=>setNotice("")}>{notice} ×</button>}
   {tab==="Home"&&<Home stories={stories} posts={posts} composer={composer} setComposer={setComposer} publish={publish} like={like} setTab={setTab}/>}
   {tab==="Discover"&&<Discover setTab={setTab}/>}
   {tab==="Create"&&<Create composer={composer} setComposer={setComposer} publish={publish}/>}
   {tab==="Reels"&&<Reels/>}
   {tab==="Messages"&&<Messages/>}
   {tab==="Profile"&&<Profile setTab={setTab}/>}
   {tab==="Communities"&&<Communities joined={joined} setJoined={setJoined}/>}
   {tab==="Notifications"&&<Notifications/>}
  </section>
  <aside className="ig-right"><ProfileMini/><div className="right-title">Suggested for you <button onClick={()=>setTab("Discover")}>See All</button></div>{["Nethmi Designs","Ravin Codes","Sahan Space"].map((x,i)=><div className="suggest" key={x}><div className="avatar">{["ND","RC","SS"][i]}</div><span><strong>{x}</strong><small>{["UI Designer","Python Builder","Astronomy"][i]}</small></span><button>Follow</button></div>)}<div className="right-title space">Trending communities</div>{["Coding","Space & Astronomy","Game Development","Mathematics"].map(x=><button className="trend" key={x} onClick={()=>setJoined(j=>j.includes(x)?j.filter(a=>a!==x):[...j,x])}><span>#{x.replaceAll(" ","")}</span><small>{joined.includes(x)?"Joined":"Join"}</small></button>)}<footer>© 2026 VEXORA · Privacy · About · Communities · Case Study</footer></aside>
 </main>
}

function Home({stories,posts,composer,setComposer,publish,like,setTab}:{stories:string[][];posts:Post[];composer:string;setComposer:(x:string)=>void;publish:()=>void;like:(x:number)=>void;setTab:(x:string)=>void}){
 return <div className="home"><div className="stories">{stories.map(([initials,name])=><button key={name} onClick={()=>setTab("Profile")}><div className="story-ring"><div className="avatar">{initials}</div></div><span>{name}</span></button>)}</div><section className="quick-create"><div className="avatar">VT</div><input value={composer} onChange={e=>setComposer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&publish()} placeholder="Share a project, idea, question..." /><button onClick={publish}>Post</button></section><div className="feed-label"><strong>For you</strong><button>Following</button></div>{posts.map(p=><article className="ig-post" key={p.id}><header><div className="avatar">{p.initials}</div><div><strong>{p.name}</strong><span>{p.time} · {p.topic}</span></div><button>•••</button></header><div className={"post-art "+p.image.toLowerCase().replace(" ","-")}><div><span>{p.image==="SPACE"?"✦":p.image==="MATH"?"∑":"⌁"}</span><strong>{p.image==="SPACE"?"EXPLORE THE UNIVERSE":p.image==="MATH"?"THINK DIFFERENT":"BUILD SOMETHING"} </strong><small>VEXORA</small></div></div><div className="post-tools"><button className={p.liked?"red":""} onClick={()=>like(p.id)}>♡</button><button>◌</button><button>↗</button><button className="save">⌑</button></div><div className="post-likes">{p.likes.toLocaleString()} likes</div><p><strong>{p.name}</strong> {p.caption}</p><button className="comments" onClick={()=>alert("Comments are coming to the prototype.")}>View all {p.comments} comments</button><div className="comment-box"><input placeholder="Add a comment..." /><button>Post</button></div></article>)}</div>
}

function ProfileMini(){return <div className="profile-mini"><div className="avatar big">VT</div><span><strong>Your Profile</strong><small>@yourprofile · Student creator</small></span><button>Switch</button></div>}
function Discover({setTab}:{setTab:(x:string)=>void}){return <div className="explore"><h1>Discover</h1><div className="search-big">⌕ <input placeholder="Search people, projects, communities and topics"/></div><div className="explore-grid">{["CODING","SPACE","DESIGN","GAMES","MATH","SCIENCE","HARDWARE","ART"].map((x,i)=><button key={x} onClick={()=>setTab("Communities")} className={"explore-tile t"+i}><span>{["⌘","✦","◇","△","∑","⚗","⌁","✧"][i]}</span><strong>{x}</strong></button>)}</div><h2>People you may know</h2><div className="people-grid">{["Nethmi Designs","Ravin Codes","Kavya Math","Sahan Space"].map((x,i)=><div className="people-card" key={x}><div className="avatar big">{["ND","RC","KM","SS"][i]}</div><strong>{x}</strong><small>Student creator · {["Design","Coding","Mathematics","Space"][i]}</small><button>Follow</button></div>)}</div></div>}
function Create({composer,setComposer,publish}:{composer:string;setComposer:(x:string)=>void;publish:()=>void}){return <div className="create-page"><h1>Create</h1><div className="create-box"><div className="create-preview"><div className="post-art YOUR-POST"><div><span>＋</span><strong>Your post</strong><small>PROJECT · IDEA · QUESTION</small></div></div></div><div className="create-form"><div className="create-author"><div className="avatar">VT</div><strong>Your Profile</strong></div><textarea value={composer} onChange={e=>setComposer(e.target.value)} placeholder="Write a caption, idea or question..."/><div className="create-options"><button>▧ Add photo</button><button>◈ Project</button><button># Topic</button><button>⌁ Opportunity</button></div><button className="share-btn" onClick={publish}>Share to VEXORA</button></div></div></div>}
function Reels(){return <div className="reels"><h1>Reels</h1><p>Short creative videos from students — prototypes, experiments, art, science and ideas.</p><div className="reel-grid">{["BUILD","SPACE","CODE","CREATE","MATH","ART"].map((x,i)=><div className={"reel r"+i} key={x}><span>{["▶","✦","⌘","⚡","∑","✧"][i]}</span><strong>{x}</strong><small>VEXORA</small><button>▶</button></div>)}</div></div>}
function Messages(){return <div className="messages"><h1>Messages</h1><div className="dm-panel"><div className="dm-list">{["Ariyan Builds","VEXORA Team","Kavya Math"].map((x,i)=><button key={x} className={i===0?"active":""}><div className="avatar">{["AB","VT","KM"][i]}</div><span><strong>{x}</strong><small>{i===0?"Can you check my project?":"New message"}</small></span></button>)}</div><div className="dm-chat"><div className="chat-top"><div className="avatar">AB</div><strong>Ariyan Builds</strong></div><div className="chat-bubble">Can you check my new project? ⚡</div><div className="chat-bubble mine">Sure! Send it here.</div><div className="chat-input"><input placeholder="Message..."/><button>Send</button></div></div></div></div>}
function Communities({joined,setJoined}:{joined:string[];setJoined:(x:string[])=>void}){const cs=["Coding","Space & Astronomy","Game Development","Mathematics","Design","Science"];return <div className="communities"><h1>Communities</h1><p>Find your people. Build around what you care about.</p><div className="community-grid">{cs.map((x,i)=><article key={x}><div className="community-art">{["⌘","✦","△","∑","◇","⚗"][i]}</div><h2>{x}</h2><span>{[2400,1800,1200,980,740,630][i].toLocaleString()} students</span><p>Share work, ask questions and collaborate with students interested in {x.toLowerCase()}.</p><button onClick={()=>setJoined(joined.includes(x)?joined.filter(a=>a!==x):[...joined,x])}>{joined.includes(x)?"Joined ✓":"Join"}</button></article>)}</div></div>}
function Notifications(){return <div className="notifications"><h1>Notifications</h1>{["Ariyan liked your project.","Kavya commented on your post.","VEXORA Team invited you to Coding.","Sahan started following you.","Innovation Showcase is now open."].map((x,i)=><div className="notification" key={x}><div className="avatar">{["♡","◌","⌘","＋","★"][i]}</div><span><strong>{x}</strong><small>{i+1}h ago</small></span><button>›</button></div>)}</div>}
function Profile({setTab}:{setTab:(x:string)=>void}){return <div className="profile-page"><div className="profile-cover"></div><div className="profile-head"><div className="avatar profile-avatar">VT</div><div><h1>Your Profile</h1><span>@yourprofile · Student creator</span><p>Building things, exploring ideas and finding people to build with.</p></div><button onClick={()=>setTab("Create")}>Edit profile</button></div><div className="profile-tabs"><button>Posts</button><button>Projects</button><button>Communities</button><button>About</button></div><div className="profile-content"><h2>7 projects</h2><div className="mini-projects">{["NFC Jukebox","CPU Simulator","VEXORA"].map(x=><div key={x}><div className="project-art">{x.slice(0,2)}</div><strong>{x}</strong><small>Project · VEXORA</small></div>)}</div></div></div>}
