import Link from "next/link";

const posts:Record<string,{name:string;topic:string;caption:string;description:string;problem:string;insight:string;challenge:string}> = {
"1":{name:"Kavya Math",topic:"Mathematics",caption:"Can you solve this without a calculator? If x + 1/x = 5, what is x² + 1/x²?",description:"A classic algebra transformation.",problem:"Find x² + 1/x² when x + 1/x = 5.",insight:"Squaring gives 25 = x² + 2 + 1/x², so the target expression is 23.",challenge:"Can you create another identity-based problem?"},
"2":{name:"Ravin Codes",topic:"Computer Science",caption:"Why does binary make computers possible?",description:"Every photo, game, message and program eventually becomes information represented by bits.",problem:"How can computers represent complex information using simple electronic states?",insight:"Binary provides a two-state representation that maps naturally onto digital switching.",challenge:"Build a tiny binary or CPU simulator and explain one instruction."},
"3":{name:"Nethmi Designs",topic:"History",caption:"The printing press changed more than books.",description:"Mechanical movable-type printing increased the speed and scale at which written material could be reproduced.",problem:"How can a communication technology change who gets access to ideas?",insight:"Faster reproduction allowed written ideas to travel beyond small circles that traditionally controlled manuscripts.",challenge:"Find one modern technology that changed how students access information."}
};

export default async function PostPage({params}:{params:Promise<{id:string}>}) {
 const {id}=await params; const p=posts[id];
 if(!p) return <main style={{minHeight:"100vh",background:"#070809",color:"#f5f7fa",padding:"48px",fontFamily:"Manrope,Arial"}}><Link href="/beat">← Back to BEAT</Link><h1>Post not found</h1><p>This post may have been removed or is not available.</p></main>;
 return <main style={{minHeight:"100vh",background:"#070809",color:"#f5f7fa",padding:"32px",fontFamily:"Manrope,Arial"}}><div style={{maxWidth:760,margin:"0 auto"}}><Link href="/beat" style={{color:"#a99aff",textDecoration:"none"}}>← Back to BEAT</Link><article style={{marginTop:32,border:"1px solid #23262c",borderRadius:18,padding:28,background:"#0d0f12"}}><div style={{color:"#858b96",fontSize:12}}>{p.topic} · BEAT</div><h1 style={{fontSize:"clamp(30px,5vw,52px)",lineHeight:1.05,margin:"12px 0"}}>{p.caption}</h1><p style={{color:"#b8bdc7",lineHeight:1.7}}>{p.description}</p><div style={{display:"grid",gap:16,marginTop:28}}>{[["PROBLEM",p.problem],["INSIGHT",p.insight],["CHALLENGE",p.challenge]].map(([label,text])=><section key={label} style={{borderTop:"1px solid #23262c",paddingTop:16}}><strong style={{color:"#9d8cff",fontSize:12,letterSpacing:1.5}}>{label}</strong><p style={{lineHeight:1.65,color:"#e5e7eb"}}>{text}</p></section>)}</div><div style={{marginTop:28,color:"#777d88"}}>Shared by <strong style={{color:"#f5f7fa"}}>{p.name}</strong></div></article></div></main>
}
